### ISSUE TITLE
Calculation of contact pressure from stress tensor at node

### ISSUE THREAD

**Issue by nicolasmecamas** [tkoziara/solfec#61]
[Contact path test.docx](https://github.com/tkoziara/solfec/files/916618/Contact.path.test.docx)
Hi developer,
Could you show me how I calculate the contact pressure from the stress tensor at nodes.
For exemple,  I would like to calculate the contact pressure for Contact path test (see attached file). 
I found the stress tensor at nodes like that:
	SX	SY	SZ	SXY	SXZ	SYZ
N1	5165,27182	4629,72709	-35602,27726	607,59127	-3269,48702	-3276,5735
N2	7682,84455	5936,261	-28521,71021	605,97911	2284,78696	2282,94985
N3	5165,33283	4629,574	-35595,90107	-606,47833	3270,45385	3275,79014

And if I use continuum mechanic to calculate the pressure on a face of normal vector n = (n1,n2,n3) (n=(0,0,1) in this test), i can't find the contact pressure of 40 000 Pa. 

Thank you in advance for your help,
Nicolas

**Comment by tkoziara** [comment]
Hi;

There is few things that need to be taken into account:

1) When you use the [STRESS](http://parmes.org/solfec/user/results.html#stress) routine to read stress values will be evaluated at an individual point of just one element (randomly picked, if this point corresponds to several element - like in case of a node); This is the way this function is implemented right now; _I think I can easily include averaging from neighbouring elements, incase the point coincides with a node - since such functionality is already there, but not used in this case_;

2) In Solfec viewer stress at nodes is averaged from the neighbouring elements; Also this is the case for the stress exported in the [XMDF](http://parmes.org/solfec/user/results.html#xdmf-export) format;

3) Contact formulation in Solfec employs point forces and not contact patches or any type of "mortar" approach; Inherently this will produce a rather poor resolution of stress at contact surfaces and will not pass a contact patch test simply by design;

So, re 1:), I will try to offer a quick resolution and let you know when it is ready; re 3), once you have some nice input decks to run and test and produce stress plots - we can use them as a basis of refining contact formulation in Solfec so that it can also reproduce stress for such cases; it would be OK to look into this, so thank you for doing this work:) In fact, thank you for looking into Solfec in all areas!:)

Best regards,
Tomek

**Comment by tkoziara** [comment]
By the way: contact stress averaging at mesh nodes should now work, when you access stress via Python; you need to update to newest sources for this; T.

**Comment by nicolasmecamas** [comment]
Hi Tomek,

I have updated the version and I obtain new stress tensor at nodes. However, I can not obtain a good stress at nodes. Could you take a look on my test in attached files. You should change the file "Test_contrainte.py.docx" to "Test_contrainte.py" because the side doest not support python file.

In the file "Contrainte2.xlsx", you will see the stress tensor at nodes N1 to N6. From these tensors, I calculated the pressure contact by the formulation n.S.n where n is the normal to the face (n=(0,0,1)) and S is stress tensor. So, I can not find the contact pressure of 40 000 Pa.

Thank you in advance for your help.

Have a nice wk,

Nicolas



[Contrainte2.xlsx](https://github.com/tkoziara/solfec/files/923734/Contrainte2.xlsx)
[Test_contrainte.py.docx](https://github.com/tkoziara/solfec/files/923735/Test_contrainte.py.docx)

**Comment by tkoziara** [comment]
Hi Nicolas,

This is a very nice test. Thank you; And yes -- it cannot work really:) This is because Solfec uses only two contact points to support the entire contact surface, where there is way more kinematic freedom. We have 4 nodes on the upper contact surface and 6 nodes on the lower one; looking only at the z-direction there are 10 displacement degrees of freedom to resolve with only two z-oriented contact force components; this is approximate thinking, since stress comes via differentiation of displacement; Nonetheless, stress is underrepresented by the two contact forces at the contact interface and therefore - as things are implemented now - you cannot resolve back the applied pressure; mesh refinement will not fix this either since Solfec will just create one contact point per element-to-element contact pair;

To fix this a surface-to-surface contact approach would need to be implemented;

One interesting test to make in terms of testing stress retrial at nodes alone - would be to have just one body with pressure applied (like your upper body in the example) and then read back the stress;
If you would like to try this, let me know how it worked out;

Best regards,
Tomek

**Comment by nicolasmecamas** [comment]
Hi Tomek,

Thank you for your efficiency.

I performed two tests: one body and two bodies with 40 MPa of applied pressure. You will find enclosed files the seconde test. Indeed, these two test yield node stress szz=40 MPa. 

The question arises why the previous test with three bodies does not give szz=40MPa?

Could you please explain this observation?

Thank you in advance,

Nicolas
[Test_contrainte_V2.py.docx](https://github.com/tkoziara/solfec/files/945552/Test_contrainte_V2.py.docx)
[Contrainte3.xlsx](https://github.com/tkoziara/solfec/files/945553/Contrainte3.xlsx)

**Comment by tkoziara** [comment]
Hi Nicolas,

I modified your script into V2.1 (attached). It now includes a header as follows:

`step=1E-4`
`stop=step*100 # (too many steps are not needed to test stress)`
`Res_Haut = 4 # upper mesh resolution`
`Res_Bas = 5 # lower mesh resolution`
`Kind_Bas = 'FINITE_ELEMENT' # base body kinematic model`
`GEOMETRIC_EPSILON (1E-4) # 0.1 mm geometrical accuracy helps to stabilize contact point locations`
`#Solver=GAUSS_SEIDEL_SOLVER (1E-4, 1000)`
`Solver = NEWTON_SOLVER ()`

This way you can have an arbitrary resolution of the upper and the lower mesh; and also use either 'OBSTACLE' or a finite element base body;

One modification was to increase GEOMETRIC_EPSILON to a value relative to the actual dimensions of the model; Contact detection now becomes more stable and contact points do not easily disappear or wander around due to roundoff error; This helps to stabilise the stress response;

Another modification in the file was to replace FIX_POINT with FIX_DIRECTION (Z-wise) in order to allow (X,Y)-expansion of the lower body; This way Poisson effect base distortion of the lower mesh is avoided and a Z-direction-dominant stress response is encouraged;

I added other convenience features such as [DISPLAY_POINTS](http://parmes.org/solfec/user/utilities.html#display-point) (see comment) and printing out of stress at the end of the file if Solfec is in 'READ' mode;

All to all, it seems that my earlier estimate of the likely efficiency of this test was somewhat pessimistic; Please, feel free to test various upper and lower resolutions; From few moments of testing I had, it seems like the stress representation is OK, given the limitations of the current point-based contact resolution technique (we can go more into details of this as needed);

Have a look into the modified file (below);
Best regards,
Tomek

[Test_contrainte_V2.1.py.txt](https://github.com/tkoziara/solfec/files/946619/Test_contrainte_V2.1.py.txt)

**Comment by nicolasmecamas** [comment]
Hi Tomek,
Thank you for your help. It works well now :)
Have a nice week,
Nicolas
